language: php
dist: trusty

notifications:
  email: false

sudo: required

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - PRODUCT_NAME=suite

    - php: 7.3
      env:
        - PRODUCT_NAME=b2c-demo-shop

    - php: 7.3
      env:
        - PRODUCT_NAME=b2b-demo-shop

services:
  - postgresql
  - redis
  - rabbitmq

addons:
  postgresql: "12"

  apt:
    packages:
      - graphviz

  hosts:
    - zed.de.spryker.test
    - www.de.spryker.test

env:
  global:
    - APPLICATION_ENV=ci.pgsql
    - SPRYKER_TESTING_ENABLED=1
    - APPLICATION_STORE=DE
    - MODULE_DIR=module
    - SHOP_DIR=current
    - MODULE_NAME=coremedia
    - POSTGRES_PORT=5433

cache:
  directories:
    - $SHOP_DIR/current/vendor
    - $HOME/.composer/cache

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini

script:
  - git clone -b bugfix/spryker-shop-suite-contains-no-ci-scripts --single-branch https://github.com/spryker-eco/eco-ci.git ecoci
  - ./ecoci/build/travis.sh
